import type { Confederation } from '../src/lib/types.ts';

export type Wc2026Entry = {
  code: string;
  name: string;
  confederation: Confederation;
  wpHistory: string | null;
  wpTeam: string;
  flagFile: string;
};

export const WC2026_TEAMS: Wc2026Entry[] = [
  // CONCACAF (6) — three hosts plus three qualifiers
  {
    code: 'CAN',
    name: 'Canada',
    confederation: 'CONCACAF',
    wpHistory: 'Canada_at_the_FIFA_World_Cup',
    wpTeam: "Canada_men's_national_soccer_team",
    flagFile: 'Flag_of_Canada_(Pantone).svg',
  },
  {
    code: 'CUW',
    name: 'Curaçao',
    confederation: 'CONCACAF',
    wpHistory: null,
    wpTeam: 'Curaçao_national_football_team',
    flagFile: 'Flag_of_Curaçao.svg',
  },
  {
    code: 'HAI',
    name: 'Haiti',
    confederation: 'CONCACAF',
    wpHistory: 'Haiti_at_the_FIFA_World_Cup',
    wpTeam: 'Haiti_national_football_team',
    flagFile: 'Flag_of_Haiti.svg',
  },
  {
    code: 'MEX',
    name: 'Mexico',
    confederation: 'CONCACAF',
    wpHistory: 'Mexico_at_the_FIFA_World_Cup',
    wpTeam: 'Mexico_national_football_team',
    flagFile: 'Flag_of_Mexico.svg',
  },
  {
    code: 'PAN',
    name: 'Panama',
    confederation: 'CONCACAF',
    wpHistory: 'Panama_at_the_FIFA_World_Cup',
    wpTeam: 'Panama_national_football_team',
    flagFile: 'Flag_of_Panama.svg',
  },
  {
    code: 'USA',
    name: 'United States',
    confederation: 'CONCACAF',
    wpHistory: 'United_States_at_the_FIFA_World_Cup',
    wpTeam: "United_States_men's_national_soccer_team",
    flagFile: 'Flag_of_the_United_States.svg',
  },

  // CONMEBOL (6)
  {
    code: 'ARG',
    name: 'Argentina',
    confederation: 'CONMEBOL',
    wpHistory: 'Argentina_at_the_FIFA_World_Cup',
    wpTeam: 'Argentina_national_football_team',
    flagFile: 'Flag_of_Argentina.svg',
  },
  {
    code: 'BRA',
    name: 'Brazil',
    confederation: 'CONMEBOL',
    wpHistory: 'Brazil_at_the_FIFA_World_Cup',
    wpTeam: 'Brazil_national_football_team',
    flagFile: 'Flag_of_Brazil.svg',
  },
  {
    code: 'COL',
    name: 'Colombia',
    confederation: 'CONMEBOL',
    wpHistory: 'Colombia_at_the_FIFA_World_Cup',
    wpTeam: 'Colombia_national_football_team',
    flagFile: 'Flag_of_Colombia.svg',
  },
  {
    code: 'ECU',
    name: 'Ecuador',
    confederation: 'CONMEBOL',
    wpHistory: 'Ecuador_at_the_FIFA_World_Cup',
    wpTeam: 'Ecuador_national_football_team',
    flagFile: 'Flag_of_Ecuador.svg',
  },
  {
    code: 'PAR',
    name: 'Paraguay',
    confederation: 'CONMEBOL',
    wpHistory: 'Paraguay_at_the_FIFA_World_Cup',
    wpTeam: 'Paraguay_national_football_team',
    flagFile: 'Flag_of_Paraguay.svg',
  },
  {
    code: 'URU',
    name: 'Uruguay',
    confederation: 'CONMEBOL',
    wpHistory: 'Uruguay_at_the_FIFA_World_Cup',
    wpTeam: 'Uruguay_national_football_team',
    flagFile: 'Flag_of_Uruguay.svg',
  },

  // AFC (9)
  {
    code: 'AUS',
    name: 'Australia',
    confederation: 'AFC',
    wpHistory: 'Australia_at_the_FIFA_World_Cup',
    wpTeam: "Australia_men's_national_soccer_team",
    flagFile: 'Flag_of_Australia.svg',
  },
  {
    code: 'IRN',
    name: 'Iran',
    confederation: 'AFC',
    wpHistory: 'Iran_at_the_FIFA_World_Cup',
    wpTeam: 'Iran_national_football_team',
    flagFile: 'Flag_of_Iran.svg',
  },
  {
    code: 'IRQ',
    name: 'Iraq',
    confederation: 'AFC',
    wpHistory: 'Iraq_at_the_FIFA_World_Cup',
    wpTeam: 'Iraq_national_football_team',
    flagFile: 'Flag_of_Iraq.svg',
  },
  {
    code: 'JOR',
    name: 'Jordan',
    confederation: 'AFC',
    wpHistory: null,
    wpTeam: 'Jordan_national_football_team',
    flagFile: 'Flag_of_Jordan.svg',
  },
  {
    code: 'JPN',
    name: 'Japan',
    confederation: 'AFC',
    wpHistory: 'Japan_at_the_FIFA_World_Cup',
    wpTeam: 'Japan_national_football_team',
    flagFile: 'Flag_of_Japan.svg',
  },
  {
    code: 'KOR',
    name: 'South Korea',
    confederation: 'AFC',
    wpHistory: 'South_Korea_at_the_FIFA_World_Cup',
    wpTeam: 'South_Korea_national_football_team',
    flagFile: 'Flag_of_South_Korea.svg',
  },
  {
    code: 'KSA',
    name: 'Saudi Arabia',
    confederation: 'AFC',
    wpHistory: 'Saudi_Arabia_at_the_FIFA_World_Cup',
    wpTeam: 'Saudi_Arabia_national_football_team',
    flagFile: 'Flag_of_Saudi_Arabia.svg',
  },
  {
    code: 'QAT',
    name: 'Qatar',
    confederation: 'AFC',
    wpHistory: 'Qatar_at_the_FIFA_World_Cup',
    wpTeam: 'Qatar_national_football_team',
    flagFile: 'Flag_of_Qatar.svg',
  },
  {
    code: 'UZB',
    name: 'Uzbekistan',
    confederation: 'AFC',
    wpHistory: null,
    wpTeam: 'Uzbekistan_national_football_team',
    flagFile: 'Flag_of_Uzbekistan.svg',
  },

  // CAF (10)
  {
    code: 'ALG',
    name: 'Algeria',
    confederation: 'CAF',
    wpHistory: 'Algeria_at_the_FIFA_World_Cup',
    wpTeam: 'Algeria_national_football_team',
    flagFile: 'Flag_of_Algeria.svg',
  },
  {
    code: 'CIV',
    name: "Côte d'Ivoire",
    confederation: 'CAF',
    wpHistory: 'Ivory_Coast_at_the_FIFA_World_Cup',
    wpTeam: 'Ivory_Coast_national_football_team',
    flagFile: "Flag_of_Côte_d'Ivoire.svg",
  },
  {
    code: 'COD',
    name: 'DR Congo',
    confederation: 'CAF',
    wpHistory: 'DR_Congo_at_the_FIFA_World_Cup',
    wpTeam: 'DR_Congo_national_football_team',
    flagFile: 'Flag_of_the_Democratic_Republic_of_the_Congo.svg',
  },
  {
    code: 'CPV',
    name: 'Cape Verde',
    confederation: 'CAF',
    wpHistory: null,
    wpTeam: 'Cape_Verde_national_football_team',
    flagFile: 'Flag_of_Cape_Verde.svg',
  },
  {
    code: 'EGY',
    name: 'Egypt',
    confederation: 'CAF',
    wpHistory: 'Egypt_at_the_FIFA_World_Cup',
    wpTeam: 'Egypt_national_football_team',
    flagFile: 'Flag_of_Egypt.svg',
  },
  {
    code: 'GHA',
    name: 'Ghana',
    confederation: 'CAF',
    wpHistory: 'Ghana_at_the_FIFA_World_Cup',
    wpTeam: 'Ghana_national_football_team',
    flagFile: 'Flag_of_Ghana.svg',
  },
  {
    code: 'MAR',
    name: 'Morocco',
    confederation: 'CAF',
    wpHistory: 'Morocco_at_the_FIFA_World_Cup',
    wpTeam: 'Morocco_national_football_team',
    flagFile: 'Flag_of_Morocco.svg',
  },
  {
    code: 'RSA',
    name: 'South Africa',
    confederation: 'CAF',
    wpHistory: 'South_Africa_at_the_FIFA_World_Cup',
    wpTeam: 'South_Africa_national_football_team',
    flagFile: 'Flag_of_South_Africa.svg',
  },
  {
    code: 'SEN',
    name: 'Senegal',
    confederation: 'CAF',
    wpHistory: 'Senegal_at_the_FIFA_World_Cup',
    wpTeam: 'Senegal_national_football_team',
    flagFile: 'Flag_of_Senegal.svg',
  },
  {
    code: 'TUN',
    name: 'Tunisia',
    confederation: 'CAF',
    wpHistory: 'Tunisia_at_the_FIFA_World_Cup',
    wpTeam: 'Tunisia_national_football_team',
    flagFile: 'Flag_of_Tunisia.svg',
  },

  // OFC (1)
  {
    code: 'NZL',
    name: 'New Zealand',
    confederation: 'OFC',
    wpHistory: 'New_Zealand_at_the_FIFA_World_Cup',
    wpTeam: "New_Zealand_men's_national_football_team",
    flagFile: 'Flag_of_New_Zealand.svg',
  },

  // UEFA (16)
  {
    code: 'AUT',
    name: 'Austria',
    confederation: 'UEFA',
    wpHistory: 'Austria_at_the_FIFA_World_Cup',
    wpTeam: 'Austria_national_football_team',
    flagFile: 'Flag_of_Austria.svg',
  },
  {
    code: 'BEL',
    name: 'Belgium',
    confederation: 'UEFA',
    wpHistory: 'Belgium_at_the_FIFA_World_Cup',
    wpTeam: 'Belgium_national_football_team',
    flagFile: 'Flag_of_Belgium_(civil).svg',
  },
  {
    code: 'BIH',
    name: 'Bosnia and Herzegovina',
    confederation: 'UEFA',
    wpHistory: 'Bosnia_and_Herzegovina_at_the_FIFA_World_Cup',
    wpTeam: 'Bosnia_and_Herzegovina_national_football_team',
    flagFile: 'Flag_of_Bosnia_and_Herzegovina.svg',
  },
  {
    code: 'CRO',
    name: 'Croatia',
    confederation: 'UEFA',
    wpHistory: 'Croatia_at_the_FIFA_World_Cup',
    wpTeam: 'Croatia_national_football_team',
    flagFile: 'Flag_of_Croatia.svg',
  },
  {
    code: 'CZE',
    name: 'Czech Republic',
    confederation: 'UEFA',
    wpHistory: 'Czech_Republic_at_the_FIFA_World_Cup',
    wpTeam: 'Czech_Republic_national_football_team',
    flagFile: 'Flag_of_the_Czech_Republic.svg',
  },
  {
    code: 'ENG',
    name: 'England',
    confederation: 'UEFA',
    wpHistory: 'England_at_the_FIFA_World_Cup',
    wpTeam: 'England_national_football_team',
    flagFile: 'Flag_of_England.svg',
  },
  {
    code: 'ESP',
    name: 'Spain',
    confederation: 'UEFA',
    wpHistory: 'Spain_at_the_FIFA_World_Cup',
    wpTeam: 'Spain_national_football_team',
    flagFile: 'Flag_of_Spain.svg',
  },
  {
    code: 'FRA',
    name: 'France',
    confederation: 'UEFA',
    wpHistory: 'France_at_the_FIFA_World_Cup',
    wpTeam: 'France_national_football_team',
    flagFile: 'Flag_of_France.svg',
  },
  {
    code: 'GER',
    name: 'Germany',
    confederation: 'UEFA',
    wpHistory: 'Germany_at_the_FIFA_World_Cup',
    wpTeam: 'Germany_national_football_team',
    flagFile: 'Flag_of_Germany.svg',
  },
  {
    code: 'NED',
    name: 'Netherlands',
    confederation: 'UEFA',
    wpHistory: 'Netherlands_at_the_FIFA_World_Cup',
    wpTeam: 'Netherlands_national_football_team',
    flagFile: 'Flag_of_the_Netherlands.svg',
  },
  {
    code: 'NOR',
    name: 'Norway',
    confederation: 'UEFA',
    wpHistory: 'Norway_at_the_FIFA_World_Cup',
    wpTeam: 'Norway_national_football_team',
    flagFile: 'Flag_of_Norway.svg',
  },
  {
    code: 'POR',
    name: 'Portugal',
    confederation: 'UEFA',
    wpHistory: 'Portugal_at_the_FIFA_World_Cup',
    wpTeam: 'Portugal_national_football_team',
    flagFile: 'Flag_of_Portugal.svg',
  },
  {
    code: 'SCO',
    name: 'Scotland',
    confederation: 'UEFA',
    wpHistory: 'Scotland_at_the_FIFA_World_Cup',
    wpTeam: 'Scotland_national_football_team',
    flagFile: 'Flag_of_Scotland.svg',
  },
  {
    code: 'SUI',
    name: 'Switzerland',
    confederation: 'UEFA',
    wpHistory: 'Switzerland_at_the_FIFA_World_Cup',
    wpTeam: 'Switzerland_national_football_team',
    flagFile: 'Flag_of_Switzerland.svg',
  },
  {
    code: 'SWE',
    name: 'Sweden',
    confederation: 'UEFA',
    wpHistory: 'Sweden_at_the_FIFA_World_Cup',
    wpTeam: 'Sweden_national_football_team',
    flagFile: 'Flag_of_Sweden.svg',
  },
  {
    code: 'TUR',
    name: 'Turkey',
    confederation: 'UEFA',
    wpHistory: 'Turkey_at_the_FIFA_World_Cup',
    wpTeam: 'Turkey_national_football_team',
    flagFile: 'Flag_of_Turkey.svg',
  },
];

if (WC2026_TEAMS.length !== 48) {
  throw new Error(`expected 48 teams, got ${WC2026_TEAMS.length}`);
}
const codes = new Set(WC2026_TEAMS.map((t) => t.code));
if (codes.size !== 48) {
  throw new Error('duplicate FIFA codes in WC2026_TEAMS');
}
